name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # Set permissions for provenance and OIDC token (optional but good practice)
    permissions:
      contents: read
      packages: write
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub

        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Extract Docker metadata for smart tagging
      - name: Extract Docker metadata

        id: meta
        uses: docker/metadata-action@v5

        with:
          # IMPORTANT: Replace 'hello-bun-app' with your image name
          images: ${{ vars.DOCKERHUB_USERNAME }}/hello-bun-app

      # Step 4: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      # Step 5: Build, push, and cache the Docker image
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          # Only push the image on pushes to the 'main' branch, not on pull requests
          push: ${{ github.event_name != 'pull_request' }}
          # Use tags generated by the metadata action
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Enable caching to speed up subsequent builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Generate provenance and SBOM for supply chain security
          provenance: true
          sbom: true
